import React from "react";

function LikeButton() {
  return <div className="like">
     <i class="fa-solid fa-heart"></i>

     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere accusantium eligendi similique mollitia magni nemo, unde aspernatur aperiam laboriosam inventore omnis quo eum soluta itaque. Provident, fugiat optio! Incidunt iste corporis sequi minus, dignissimos consequatur eveniet blanditiis optio. Neque eum magni in et enim pariatur ipsam iure odio laudantium. Facere, consequatur tempore nihil, reiciendis, voluptatibus delectus voluptas cum laborum quae aliquam totam ipsam iure reprehenderit! Sit, enim sed! Corporis corrupti vero facilis veritatis officia eaque, hic quis debitis? Autem, perspiciatis quibusdam et, eum ab non reprehenderit beatae suscipit esse ratione quis obcaecati nostrum eligendi amet nulla fugit, recusandae maiores quo!</p>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere accusantium eligendi similique mollitia magni nemo, unde aspernatur aperiam laboriosam inventore omnis quo eum soluta itaque. Provident, fugiat optio! Incidunt iste corporis sequi minus, dignissimos consequatur eveniet blanditiis optio. Neque eum magni in et enim pariatur ipsam iure odio laudantium. Facere, consequatur tempore nihil, reiciendis, voluptatibus delectus voluptas cum laborum quae aliquam totam ipsam iure reprehenderit! Sit, enim sed! Corporis corrupti vero facilis veritatis officia eaque, hic quis debitis? Autem, perspiciatis quibusdam et, eum ab non reprehenderit beatae suscipit esse ratione quis obcaecati nostrum eligendi amet nulla fugit, recusandae maiores quo!</p>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere accusantium eligendi similique mollitia magni nemo, unde aspernatur aperiam laboriosam inventore omnis quo eum soluta itaque. Provident, fugiat optio! Incidunt iste corporis sequi minus, dignissimos consequatur eveniet blanditiis optio. Neque eum magni in et enim pariatur ipsam iure odio laudantium. Facere, consequatur tempore nihil, reiciendis, voluptatibus delectus voluptas cum laborum quae aliquam totam ipsam iure reprehenderit! Sit, enim sed! Corporis corrupti vero facilis veritatis officia eaque, hic quis debitis? Autem, perspiciatis quibusdam et, eum ab non reprehenderit beatae suscipit esse ratione quis obcaecati nostrum eligendi amet nulla fugit, recusandae maiores quo!</p>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere accusantium eligendi similique mollitia magni nemo, unde aspernatur aperiam laboriosam inventore omnis quo eum soluta itaque. Provident, fugiat optio! Incidunt iste corporis sequi minus, dignissimos consequatur eveniet blanditiis optio. Neque eum magni in et enim pariatur ipsam iure odio laudantium. Facere, consequatur tempore nihil, reiciendis, voluptatibus delectus voluptas cum laborum quae aliquam totam ipsam iure reprehenderit! Sit, enim sed! Corporis corrupti vero facilis veritatis officia eaque, hic quis debitis? Autem, perspiciatis quibusdam et, eum ab non reprehenderit beatae suscipit esse ratione quis obcaecati nostrum eligendi amet nulla fugit, recusandae maiores quo!</p>
    
  </div>;
}
export default LikeButton;